### ISSUE TITLE
Loading levioSAM index error

### ISSUE THREAD

**Issue by balabanmetin** [langmead-lab/reference_flow#4]
I tried to align paired end whole exome sequence reads using reference_flow. I got an error during the execution of `lift_major_highq` rule. The following command generates the error:

`snakemake -j 16  run/experiments/test/wg-major-mapqgeq10-liftover.sam`

The error message is:

```
Loading levioSAM index...terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted
```

The error occurs when the following command is executed:

`leviosam lift -a run/experiments/test/wg-major-mapqgeq10.sam -l run/major/wg-major.lft -p run/experiments/test/wg-major-mapqgeq10-liftover -t 16`

I installed `leviosam` using conda. The version number is  `Version: 0.5.0-N/A`.  I am using the prebuilt RandFlow-LD index: [RandFlow-LD (22GB)](https://genome-idx.s3.amazonaws.com/bt/flow/randflow_ld.tar.gz)

Any help is appreciated.

**Comment by balabanmetin** [comment]
Update on the issue: I installed the older version of levioSAM v0.3.1.2 from conda. This seems to fix the error.

**Comment by milkschen** [comment]
Hi @balabanmetin , Thanks for the feedback!
